---
title: "Homework 12"
author: "Miles Tweed"
date: "3/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Problem 1

Read

# Problem 2

### Ch. 2 Exercise 1
```{r}
library(shiny)
library(tidyverse)


ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      textInput(inputId='text1',
                label='', 
                placeholder = 'Your name')
    ),
    mainPanel(
    )
  )
)

server <- function(session, input, output) {
  
}

shinyApp(ui = ui, server = server)
```








# Ch. 2 Exercise 2
```{r}
library(shiny)
library(tidyverse)


ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      sliderInput(inputId='date1',
                  min=as.Date("2020-09-16"),
                  max=as.Date("2020-09-23"),
                  value = as.Date("2020-09-17"), 
                  label='When should we deliver?')
    ),
    mainPanel(
    )
  )
)

server <- function(session, input, output) {
  
}

shinyApp(ui = ui, server = server)
```








# Problem 3

```{r}
library(shiny)
library(tidyverse)

wb <- read_csv("../../Data/WorldBankData.csv")
wb <- wb %>% drop_na()

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      selectInput(inputId = 'region',
                  label = 'Select a region',
                  choices = unique(wb$Region)),
    ),
    mainPanel(
      tableOutput('fert')
    )
  )
)

server <- function(session, input, output) {

  
  output$fert = renderTable(wb %>%  
                              filter(Region==input$region) %>% 
                              select('Year',
                                     'Country',
                                     'Fertility',
                                     'LifeExpectancy') %>% 
                              arrange(-Year) %>% 
                              drop_na())

  }

shinyApp(ui = ui, server = server)
```





# Problem 4

Part 1
```{r}
ui <- fluidPage(
  textInput("name", "What's your name?"),
  textOutput("greeting")
)

# server1 <- function(input, output, server) {
#   input$greeting <- renderText(paste0("Hello ", name))
# }

server1 <- function(input, output, server) {
  output$greeting <- renderText(paste0("Hello ", input$name))
}

shinyApp(ui = ui, server = server1)

```






Part 2
```{r}
ui <- fluidPage(
  textInput("name", "What's your name?"),
  textOutput("greeting")
)

# server2 <- function(input, output, server) {
#   greeting <- paste0("Hello ", input$name)
#   output$greeting <- renderText(greeting)
# }

server2 <- function(input, output, server) {
  greeting <- reactive(x = paste0("Hello ", input$name))
  output$greeting <- renderText(greeting())
}

shinyApp(ui = ui, server = server2)

```





Part 3
```{r}
ui <- fluidPage(
  textInput("name", "What's your name?"),
  textOutput("greeting")
)

server3 <- function(input, output, server) {
  output$greeting <- reactive(paste0("Hello ", input$name))
}

shinyApp(ui = ui, server = server3)
```


# Problem 5

```{r}
library(shiny)
library(plotly)
library(tidyverse)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      sliderInput(
        inputId = 'year',
        label = 'Year',
        min = min(wb$Year),
        max = max(wb$Year)-1,
        value = 2000,
        step = 1,
        sep = ""
      ),
      selectInput(
        inputId = 'regions',
        label = "Select regions",
        choices = unique(wb$Region),
        selected = NULL,
        multiple = TRUE
      ),
      selectInput(
        inputId = 'countries',
        label = 'Select countries',
        choices = NULL,
        multiple = TRUE
      ),
    ),
    mainPanel(
      plotlyOutput('scatter')
    )
  )
)



server <- function(input, output, session) {
  
  observeEvent(list(input$regions),{
    if (length(input$regions != 0)){
      df <- wb %>% filter(Region==input$regions)
      updateSelectInput(session,
                        inputId = 'countries',
                        choices = unique(df$Country))
    } 
  },ignoreInit = TRUE)
  
  
  
  df <- reactive({
      wb %>% filter(Year == input$year)
  })
  
  countries <- reactive({ input$countries })
  
  output$scatter <- renderPlotly({
                c = countries()
                
                df <- df()
                ifelse(!is.null(c),
                       df <- df %>% filter(Country==c),df)
                plot <- plot_ly(df,
                                type = 'scatter',
                                mode='markers',
                                x = ~Fertility,
                                y = ~LifeExpectancy,
                                size = ~Population,
                                color = ~Region,
                                hoverinfo = 'text',
                                text = paste0("<b>Country:</b> ", df$Country,"<br>",
                                              "<b>Life Expectancy:</b> ", df$LifeExpectancy,"<br>",
                                              "<b>Fertility Rate:</b> ", df$Fertility,"<br>",
                                              "<b>Populaion:</b> ",df$Population)
                                ) %>%
                layout(xaxis=list(title = 'Fertility Rate',
                                  range = c(0,10)),
                       yaxis=list(title = 'Life Expectancy',
                                  range = c(10,90)))
                })
}

shinyApp(ui = ui, server = server)
```




```{r}
library(reactlog)
reactlog_enable()
shinyApp(ui = ui, server = server)
## move the slider to 100 and then stop the app
reactlogShow()
```




```{r}
library(shiny)
library(plotly)
library(tidyverse)
#size = population
# x = fertility rate
# y = life Expectancy
# slider = year

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      sliderInput(
        inputId = 'year',
        label = 'Year',
        min = min(wb$Year),
        max = max(wb$Year)-1,
        value = 2000,
        step = 1,
        sep = ""
      ),
      checkboxInput(
        inputId = 'choose',
        label = 'Choose Countries?',
        value = FALSE
      ),
      uiOutput("regionselector"),
      uiOutput('countryselector'),
    ),
    mainPanel(
      plotlyOutput('scatter')
    )
  )
)

server <- function(input, output, session) {
    eventReactive(input$choose,{
      output$regionselector <- renderUI({
                              df <- wb %>% filter(Region != "North America")
                              selectInput(
                                inputId = "myregion",
                                label = "Select a Region",
                                choices = unique(df$Region)
                              )
                          })
    })

}

shinyApp(ui = ui, server = server)
```